---

- name: 01.01 packages | ensure apt list dir exists
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755

- name: 01.02 Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: 01.03 Install additional packages
  become: yes
  apt:
    pkg:
      - gpg
      - gpg-agent
      - python3
      - python3-pip
      - ufw
      - rsyslog
      - update-motd
  tags:
    - config.packages
