---
- name: 04.01 Copy cpu-performance.service systemd service file
  copy:
    src: "../files/cpu-performance.service"
    dest: /etc/systemd/system/cpu-performance.service
    mode: 0644
    owner: root
    group: root

- name: 04.02 Reload systemd
  systemd:
    daemon_reload: yes

- name: 04.03 Enable cpu-performance service
  systemd:
    name: cpu-performance
    enabled: yes
