---
- name: 05.01 Install firewall package ufw
  package:
    name:
      - ufw
    state: present
  tags:
    - config.firewall

- name: 05.02 Deny all ingress connections
  ufw:
    policy: deny
    direction: incoming
  tags:
    - config.firewall

- name: 05.03 Allow ingress ssh
  ufw:
    rule: allow
    port: ssh
    proto: tcp
    direction: in
  tags:
    - config.firewall

- name: 05.04 Allow ingress solana udp ports
  ufw:
    rule: allow
    proto: udp
    direction: in
    port: '{{ open_solana_ports_start }}:{{ open_solana_ports_end }}'
  tags:
    - config.firewall

- name: 05.05 Allow ingress solana tcp ports
  ufw:
    rule: allow
    proto: tcp
    direction: in
    port: '{{ open_solana_ports_start }}:{{ open_solana_ports_end }}'
  tags:
    - config.firewall

- name: 05.06 Enable ufw
  ufw:
    state: enabled
  tags:
    - config.firewall
