---
- name: 07.01 Ensure group specific for user "{{ solana_user }}" exists
  ansible.builtin.group:
    name: "{{ solana_user }}"
    state: present

- name: 07.02 Create "{{ solana_user }}"
  user:
    name: "{{ solana_user }}"
    state: present
    create_home: yes
    shell: /bin/bash
    skeleton: /etc/skel
    force: yes
    groups:
      - "{{ solana_user }}"
      - syslog
  tags:
    - config.solana_user
    - validator.service.solana

- name: 07.03 Create secrets dir
  become: yes
  become_user: "{{ solana_user }}"
  file:
    path: "{{ secrets_path }}"
    state: directory
    mode: '0700'
  tags:
    - config.solana_user
    - validator.service.solana

- name: 07.04 Create ledger directory
  become: yes
  file:
    path: "{{ ledger_path }}"
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    state: directory
    mode: '0755'
  tags:
    - config.solana_user
    - validator.service.solana

- name: 07.05 Set accounts path for disk
  set_fact:
    accounts_path: "{{ mount_base_path }}/accounts"
  when: not use_ramdisk_for_account
  tags:
    - config.solana_user
    - validator.service.solana

- name: 07.06 Set account path for ramdisk
  set_fact:
    accounts_path: "{{ ramdisk_path }}/accounts"
  when: use_ramdisk_for_account
  tags:
    - config.solana_user
    - validator.service.solana

- name: 07.07 Create accounts directory on disk
  become: yes
  file:
    path: "{{ accounts_path }}"
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    state: directory
    mode: '0755'
  tags:
    - config.solana_user
    - validator.service.solana

- name: 07.08 Create snapshots directory
  become: yes
  file:
    path: "{{ snapshots_path }}"
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    state: directory
    mode: '0755'
  tags:
    - config.solana_user
    - validator.service.solana

- name: 07.09 Create logs directory
  become: yes
  file:
    path: "{{ validator_log_path }}"
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    state: directory
    mode: '0755'
  tags:
    - config.solana_user
    - validator.service.solana
